Args=--no-fallback \
     --features=ca.pigggott.sample.graal.FxFeature \
     --initialize-at-run-time=java.awt.event.MouseEvent \
     --initialize-at-run-time=java.awt.dnd.DragSource \
     --initialize-at-run-time=com.sun.javafx.scene.control.ControlHelper \
     --initialize-at-run-time=sun.awt.windows \
     --initialize-at-run-time=sun.font.PhysicalStrike \
     --initialize-at-run-time=sun.font.StrikeCache \
     --initialize-at-run-time=sun.java2d.d3d.D3DGraphicsDevice \
     --initialize-at-run-time=sun.java2d.d3d.D3DSurfaceData \
     --initialize-at-run-time=com.sun.glass.ui.Application \
     --initialize-at-run-time=com.sun.glass.ui.Clipboard \
     --initialize-at-run-time=com.sun.glass.ui.View \
     --initialize-at-run-time=com.sun.glass.ui.Window \
     --initialize-at-run-time=com.sun.glass.ui.gtk \
     --initialize-at-run-time=com.sun.glass.ui.gtk.GtkApplication \
     --initialize-at-run-time=com.sun.glass.ui.gtk.GtkWindow \
     --initialize-at-run-time=com.sun.glass.ui.gtk.GtkView \
     --initialize-at-run-time=com.sun.glass.ui.gtk.GtkCursor \
     --initialize-at-run-time=com.sun.glass.ui.gtk.GtkPixels \
     --initialize-at-run-time=com.sun.glass.ui.gtk.GtkTimer \
     --initialize-at-run-time=com.sun.glass.ui.mac \
     --initialize-at-run-time=com.sun.glass.ui.win \
     --initialize-at-run-time=com.sun.glass.ui.win.WinAccessible \
     --initialize-at-run-time=com.sun.glass.ui.win.WinApplication \
     --initialize-at-run-time=com.sun.glass.ui.win.WinCursor \
     --initialize-at-run-time=com.sun.glass.ui.win.WinGestureSupport \
     --initialize-at-run-time=com.sun.glass.ui.win.WinPixels \
     --initialize-at-run-time=com.sun.glass.ui.win.WinTimer \
     --initialize-at-run-time=com.sun.glass.ui.win.WinView \
     --initialize-at-run-time=com.sun.glass.ui.win.WinWindow \
     --initialize-at-run-time=com.sun.javafx.application.PlatformImpl \
     --initialize-at-run-time=com.sun.javafx.font.AndroidFontFinder \
     --initialize-at-run-time=com.sun.javafx.font.DFontDecoder \
     --initialize-at-run-time=com.sun.javafx.font.MacFontFinder \
     --initialize-at-run-time=com.sun.javafx.font.PrismFontFactory \
     --initialize-at-run-time=com.sun.javafx.font.PrismFontFile \
     --initialize-at-run-time=com.sun.javafx.font.coretext.CTFontStrike \
     --initialize-at-run-time=com.sun.javafx.font.coretext.CTGlyph \
     --initialize-at-run-time=com.sun.javafx.font.directwrite.DWFontStrike \
     --initialize-at-run-time=com.sun.javafx.font.directwrite.OS \
     --initialize-at-run-time=com.sun.javafx.iio.jpeg.JPEGImageLoader \
     --initialize-at-run-time=com.sun.javafx.scene.NodeHelper \
     --initialize-at-run-time=com.sun.javafx.scene.control.ContextMenuContent$StyleableProperties \
     --initialize-at-run-time=com.sun.javafx.scene.control.LabeledHelper \
     --initialize-at-run-time=com.sun.javafx.scene.control.LabeledImpl$StyleableProperties \
     --initialize-at-run-time=com.sun.javafx.scene.control.Properties \
     --initialize-at-run-time=com.sun.javafx.scene.control.behavior.TextInputControlBehavior \
     --initialize-at-run-time=com.sun.javafx.scene.control.skin.FXVKSkin \
     --initialize-at-run-time=com.sun.javafx.scene.control.skin.Utils \
     --initialize-at-run-time=com.sun.javafx.text.GlyphLayoutManager \
     --initialize-at-run-time=com.sun.javafx.text.PrismTextLayoutFactory \
     --initialize-at-run-time=com.sun.javafx.tk.Toolkit \
     --initialize-at-run-time=com.sun.javafx.tk.quantum.PrismImageLoader2$AsyncImageLoader \
     --initialize-at-run-time=com.sun.javafx.tk.quantum.QuantumToolkit \
     --initialize-at-run-time=com.sun.javafx.tk.quantum.QuantumRenderer \
     --initialize-at-run-time=com.sun.javafx.tk.quantum.PaintCollector \
     --initialize-at-run-time=com.sun.javafx.webkit.prism.PrismGraphicsManager \
     --initialize-at-run-time=com.sun.marlin.DMarlinRenderingEngine \
     --initialize-at-run-time=com.sun.marlin.MarlinUtils \
     --initialize-at-run-time=com.sun.marlin.MaskMarlinAlphaConsumer \
     --initialize-at-run-time=com.sun.prism.PresentableState \
     --initialize-at-run-time=com.sun.prism.d3d.D3DPipeline \
     --initialize-at-run-time=com.sun.prism.GraphicsPipeline \
     --initialize-at-run-time=com.sun.prism.es2.ES2Pipeline \
     --initialize-at-run-time=com.sun.prism.es2.ES2Context \
     --initialize-at-run-time=com.sun.prism.es2.GLFactory \
     --initialize-at-run-time=com.sun.prism.es2.MacGLFactory \
     --initialize-at-run-time=com.sun.prism.es2.X11GLFactory \
     --initialize-at-run-time=com.sun.prism.mtl.MTLPipeline \
     --initialize-at-run-time=com.sun.prism.mtl.MTLContext \
     --initialize-at-run-time=com.sun.prism.mtl.MTLResourceFactory \
     --initialize-at-run-time=com.sun.prism.mtl.MTLTexture \
     --initialize-at-run-time=com.sun.prism.mtl.MTLRTTexture \
     --initialize-at-run-time=com.sun.prism.impl.BaseResourcePool \
     --initialize-at-run-time=com.sun.prism.impl.PrismSettings \
     --initialize-at-run-time=com.sun.prism.impl.ps.PaintHelper \
     --initialize-at-run-time=com.sun.prism.sw.SWPipeline \
     --initialize-at-run-time=com.sun.scenario.animation.AbstractPrimaryTimer \
     --initialize-at-run-time=com.sun.webkit.WebPage \
     -H:+UnlockExperimentalVMOptions \
     -J-Djava.awt.headless=false \
     -J-Dprism.verbose=true \
     -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED
