Args=--no-fallback \
     --initialize-at-run-time=javafx.application.Platform \
     --initialize-at-run-time=javafx.scene.control.Control \
     --initialize-at-run-time=javafx.scene.Node \
     --initialize-at-run-time=javafx.scene.chart.Axis$StyleableProperties \
     --initialize-at-run-time=javafx.scene.chart.CategoryAxis \
     --initialize-at-run-time=javafx.scene.chart.CategoryAxis$StyleableProperties \
     --initialize-at-run-time=javafx.scene.chart.NumberAxis$StyleableProperties \
     --initialize-at-run-time=javafx.scene.chart.ValueAxis$StyleableProperties \
     --initialize-at-run-time=javafx.scene.chart.AreaChart \
     --initialize-at-run-time=javafx.scene.chart.AreaChart$StyleableProperties \
     --initialize-at-run-time=javafx.scene.chart.BarChart \
     --initialize-at-run-time=javafx.scene.chart.BarChart$StyleableProperties \
     --initialize-at-run-time=javafx.scene.chart.Chart \
     --initialize-at-run-time=javafx.scene.chart.Chart$StyleableProperties \
     --initialize-at-run-time=javafx.scene.chart.XYChart \
     --initialize-at-run-time=javafx.scene.chart.XYChart$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.Control$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.DialogPane$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.Labeled$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.ListView$EditEvent \
     --initialize-at-run-time=javafx.scene.control.ListView$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.Pagination$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.PopupControl \
     --initialize-at-run-time=javafx.scene.control.ScrollBar$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.ScrollPane$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.Separator$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.SkinBase$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.Slider$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.SplitPane$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.TableView$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.TabPane$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.TextArea$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.TextField$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.TextInputControl$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.TreeView$EditEvent \
     --initialize-at-run-time=javafx.scene.control.TitledPane$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.skin.CellSkinBase$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.skin.PaginationSkin$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.skin.ProgressBarSkin$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.skin.ProgressIndicatorSkin \
     --initialize-at-run-time=javafx.scene.control.skin.TabPaneSkin$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.skin.TextInputControlSkin \
     --initialize-at-run-time=javafx.scene.control.skin.TextInputControlSkin$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.skin.TreeCellSkin$StyleableProperties \
     --initialize-at-run-time=javafx.scene.control.TreeView$StyleableProperties \
     --initialize-at-run-time=javafx.stage.Screen \
     --initialize-at-run-time=javafx.scene.CssStyleHelper \
     --initialize-at-run-time=javafx.scene.image.ImageView$StyleableProperties \
     --initialize-at-run-time=javafx.scene.layout.GridPane$StyleableProperties \
     --initialize-at-run-time=javafx.scene.layout.HBox$StyleableProperties \
     --initialize-at-run-time=javafx.scene.layout.Region$StyleableProperties \
     --initialize-at-run-time=javafx.scene.layout.StackPane$StyleableProperties \
     --initialize-at-run-time=javafx.scene.layout.VBox$StyleableProperties \
     --initialize-at-run-time=javafx.scene.shape.Rectangle$StyleableProperties \
     --initialize-at-run-time=javafx.scene.shape.Shape$StyleableProperties \
     --initialize-at-run-time=javafx.scene.text.Font \
     --initialize-at-run-time=javafx.scene.text.Text$StyleableProperties \
     --initialize-at-run-time=javafx.scene.web.WebEngine \
     --initialize-at-run-time=javafx.scene.web.WebView$StyleableProperties \
     -H:+UnlockExperimentalVMOptions \
     -J-Dprism.verbose=true \
     -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED
