Args=--features=ca.piggott.graal.ikonli.IkonliFeature \
     --initialize-at-run-time=org.kordamp.ikonli.javafx.FontIcon \
     --initialize-at-run-time=org.kordamp.ikonli.AbstractIkonResolver \
     --initialize-at-run-time=org.kordamp.ikonli.javafx.IkonResolver \
     --initialize-at-run-time=org.kordamp.ikonli.javafx.FontIcon \
     --initialize-at-run-time=org.kordamp.ikonli.javafx.FontIcon$StyleableProperties \
     -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED
